[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'gcc', 'pkg-config']

[phases.install]
cmds = [
  'pip install --upgrade pip setuptools wheel',
  'pip install -r requirements.txt'
]

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT main:flask_app --workers 1 --timeout 120 --threads 2'
